# Array creation

In [2]:
import numpy as np
array = np.array([[1, 2, 3], [4, 5, 6]])
array

array([[1, 2, 3],
       [4, 5, 6]])

In [2]:
array = np.zeros((2, 4))
array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [3]:
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Shape manipulation

In [7]:
import numpy as np
array = np.array([[1, 2, 3], [4, 5, 6]])
print(array.ndim, array.shape)

2 (2, 3)


In [8]:
array = np.arange(12)
array = array.reshape(2, 6)
array

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [9]:
flattened = array.ravel()
flattened

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
transposed = array.T
transposed

array([[ 0,  6],
       [ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11]])

# Types of ndarray objects

In [16]:
array = np.array([[1, 2, 3], [4, 5, 6]])
array.dtype

dtype('int64')

In [18]:
array = np.array(["hello", "world!"])
array.dtype

dtype('<U6')

In [22]:
array = np.array([[1, 2, 3], [4, 5, 6]])
print(array.dtype)
float_array = array.astype(np.float32)
print(float_array.dtype)

int64
float32


# Basic operations

In [7]:
a = np.arange(6).reshape(2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [8]:
# Operations with scalar values
a = a * 2 + 1
a

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [9]:
# Elementwise operations
sum = a + a
sum

array([[ 2,  6, 10],
       [14, 18, 22]])

In [10]:
# Elementwise product
prod = a * a
prod

array([[  1,   9,  25],
       [ 49,  81, 121]])

In [11]:
# Matrix product
dot = a @ a.T
dot

array([[ 35,  89],
       [ 89, 251]])

# Universal Functions

In [12]:
a = np.arange(6).reshape(2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [13]:
# Square root elementwise
sqrt = np.sqrt(a)
sqrt

array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798]])

In [14]:
# Universal binary function
sqrt += 1
b = np.greater(a, sqrt)
b

array([[False, False, False],
       [ True,  True,  True]])

In [15]:
# Binary comparison operator
c = a > sqrt
c

array([[False, False, False],
       [ True,  True,  True]])

# Slicing and indexing

## One-dimensional array

In [16]:
a = np.arange(12)**2
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121])

In [17]:
a[1]

1

In [18]:
# Slice from index 2 (3rd element) up to index 6 (not included)
a[2:6]

array([ 4,  9, 16, 25])

In [19]:
# Every second element from first element to index 6 (not included)
a[:6:2]

array([ 0,  4, 16])

In [20]:
# Every second element from last to 6th element from the end
a[:6:-2]

array([121,  81,  49])

## Multi-dimensional array

In [21]:
a = np.arange(20).reshape(4, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [22]:
# Element located in 3rd row and 4th column
a[2, 3]

13

In [23]:
# Slice comprising 2nd row to 4th (exclusive) and all columns
a[1:3]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [24]:
# Slice comprising all rows and 2nd to 4th column (exclusive)
a[:, 1:3]

array([[ 1,  2],
       [ 6,  7],
       [11, 12],
       [16, 17]])

## Boolean indexing

In [25]:
# Random grades from 0-10 of four students (rows) in 5 courses (columns)
students = np.array(['Bob', 'Mary', 'Joe', 'Will'])
courses = np.array(['CS101', 'CS102', 'CS103', 'CS104', 'CS105'])
grades = np.random.randint(0, 11, (4,5))
grades

array([[ 8,  5,  9,  0,  9],
       [ 2,  2,  3,  0, 10],
       [10,  7,  1,  1,  0],
       [ 4,  3,  9,  8,  5]])

In [26]:
# Select grades for Mary:
# rows that match positions of True values in Boolean array
print(students == 'Mary')
grades[students == 'Mary']

[False  True False False]


array([[ 2,  2,  3,  0, 10]])

In [27]:
# Select student grades for Courses 'CS102', 'CS103':
# columns that match positions of True values in Boolean array
grades[:, np.isin(courses, ['CS102', 'CS103'])]

array([[5, 9],
       [2, 3],
       [7, 1],
       [3, 9]])