# Array creation

In [3]:
import numpy as np
array = np.array([[1, 2, 3], [4, 5, 6]])
array

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
array = np.zeros((2, 4))
array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Shape manipulation

In [6]:
import numpy as np
array = np.array([[1, 2, 3], [4, 5, 6]])
print(array.ndim, array.shape)

2 (2, 3)


In [7]:
array = np.arange(12)
array = array.reshape(2, 6)
array

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [8]:
flattened = array.ravel()
flattened

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [9]:
transposed = array.T
transposed

array([[ 0,  6],
       [ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11]])

# Types of ndarray objects

In [10]:
array = np.array([[1, 2, 3], [4, 5, 6]])
array.dtype

dtype('int64')

In [11]:
array = np.array(["hello", "world!"])
array.dtype

dtype('<U6')

In [12]:
array = np.array([[1, 2, 3], [4, 5, 6]])
print(array.dtype)
float_array = array.astype(np.float32)
print(float_array.dtype)

int64
float32


# Basic operations

In [46]:
a = np.arange(6).reshape(2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [47]:
# Elementwise operations
sum = a + a
sum

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [48]:
# Elementwise product
prod = a * a
prod

array([[ 0,  1,  4],
       [ 9, 16, 25]])

In [39]:
array = a % 5
array

array([[0, 1, 2],
       [3, 4, 0]])

In [40]:
array = sum - a == a
array

array([[ True,  True,  True],
       [ True,  True,  True]])

In [42]:
# Matrix product
dot = a @ a.T
dot

array([[ 5, 14],
       [14, 50]])

In [45]:
# Operations with scalar values
a = a * 2 + 1
a

array([[ 1,  3,  5],
       [ 7,  9, 11]])

# Broadcasting

In [49]:
# Operations with scalar values
a = np.arange(6).reshape(2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [69]:
# array filled with ones, platform dependent int representation
b = np.ones((1, 3)).astype(np.intp)
b

array([[1, 1, 1]])

In [85]:
# broadcasting of shape (1, 3) to (2, 3)
c = b + a + a + b
c

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [86]:
# broadcast of (3, 3) to (1, 3, 1)
d = np.ones((1, 3, 1)) + np.ones((3, 3))
d

array([[[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]]])

# Universal Functions

In [ ]:
a = np.arange(6).reshape(2, 3)
a

In [ ]:
# Square root elementwise
sqrt = np.sqrt(a)
sqrt

In [ ]:
# Universal binary function
sqrt += 1
b = np.greater(a, sqrt)
b

In [ ]:
# Binary comparison operator
c = a > sqrt
c

# Slicing and indexing

## One-dimensional array

In [102]:
a = np.arange(12)**2
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121])

In [103]:
a[1]

1

In [104]:
# Slice from index 2 (3rd element) up to index 6 (not included)
a[2:6]

array([ 4,  9, 16, 25])

In [105]:
# Every second element from first element to index 6 (not included)
a[:6:2]

array([ 0,  4, 16])

In [106]:
# Every second element from last to 6th element from the end
a[:6:-2]

array([121,  81,  49])

In [109]:
# Assign zero to all slice elements,
# changes are reflected to the original array
slice = a[:6:-2]
slice[:] = 0
a

array([  0,   1,   4,   9,  16,  25,  36,   0,  64,   0, 100,   0])

## Multi-dimensional array

In [92]:
a = np.arange(20).reshape(4, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [93]:
# Element located in 3rd row and 4th column
a[2, 3]

13

In [94]:
# Slice comprising 2nd row to 4th (exclusive) and all columns
a[1:3]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [98]:
# Slice comprising all rows and 2nd to 4th column (exclusive)
b = a[:, 1:3]
b

array([[ 1,  2],
       [ 6,  7],
       [11, 12],
       [16, 17]])

In [100]:
# Assign 1 to the second column of the previous slice, 
# changes are reflected to the third column of the original array
b[:, 1] = 1
a

array([[ 0,  1,  1,  3,  4],
       [ 5,  6,  1,  8,  9],
       [10, 11,  1, 13, 14],
       [15, 16,  1, 18, 19]])

## Boolean indexing

In [110]:
# Random grades from 0-10 of four students (rows) in 5 courses (columns)
students = np.array(['Bob', 'Mary', 'Joe', 'Will'])
courses = np.array(['CS101', 'CS102', 'CS103', 'CS104', 'CS105'])
grades = np.random.randint(0, 11, (4,5))
grades

array([[ 5,  3,  2,  1, 10],
       [ 6,  0,  8,  4,  6],
       [ 7,  3,  3,  1,  7],
       [ 0,  0,  4,  0,  6]])

In [111]:
# Select grades for Mary:
# rows that match positions of True values in Boolean array
print(students == 'Mary')
grades[students == 'Mary']

[False  True False False]


array([[6, 0, 8, 4, 6]])

In [112]:
# Select student grades for Courses 'CS102', 'CS103':
# columns that match positions of True values in Boolean array
grades[:, np.isin(courses, ['CS102', 'CS103'])]

array([[3, 2],
       [0, 8],
       [3, 3],
       [0, 4]])